set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_C_COMPILER       "arm-none-eabi-gcc")
set(CMAKE_CXX_COMPILER     "arm-none-eabi-g++")
set(CMAKE_AR               "arm-none-eabi-ar" CACHE FILEPATH "" FORCE)
set(BUILD                  GBA)
